# Generated by Django 5.1.6 on 2025-06-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancerequest",
            unique_together={("student", "date_requested")},
        ),
    ]
